#!/usr/bin/env python3
"""Generate the app stylesheets the theme ships, from colors.toml.

    tools/appcss.py            # writes obsidian.css and the share-picker css for both tones

Obsidian: Inter for the interface, Newsreader (falling back to Noto Serif)
for note text, monospace only inside code; radius 24, padding 24, hairline
surfaces, two text tones, neutral headings, chips for tags.
"""
import re, pathlib
ROOT = pathlib.Path(__file__).resolve().parent.parent

def toml(p):
    d = {}
    for l in open(p):
        m = re.match(r'^\s*([A-Za-z0-9_-]+)\s*=\s*"([^"]*)"', l)
        if m: d[m.group(1)] = m.group(2)
    return d
def rgb(h): return ",".join(str(int(h[i:i+2], 16)) for i in (1, 3, 5))

def obsidian(c, light):
    base, raised, fg, muted, accent, sel = c["background"], c["lighter_background"], c["foreground"], c["muted"], c["accent"], c["selection"]
    shadow = "0 8px 32px rgba(0,0,0,.06)" if light else "0 8px 32px rgba(0,0,0,.28)"
    return f"""/* Marvin for Obsidian — {'light' if light else 'dark'}. Generated by tools/appcss.py
   from colors.toml. The design system applied to the Notes app: Inter for
   the interface, a serif for the notes themselves, monospace only inside
   code; radius 24, padding 24, hairline surfaces, two text tones, neutral
   headings, chips for tags. */

body {{
  --font-interface-theme: "Inter", sans-serif;
  --font-text-theme: "Newsreader", "Noto Serif", serif;
  --font-monospace-theme: "JetBrains Mono", monospace;
  --font-text-size: 17px;
  --font-ui-smaller: 12px;
  --font-ui-small: 12px;
  --font-ui-medium: 14px;
  --font-ui-large: 16px;
  --line-height-normal: 1.6;
  --file-line-width: 40em;
  --radius-s: 12px;
  --radius-m: 24px;
  --radius-l: 24px;
  --radius-xl: 24px;
  --tab-radius: 20px;
  --input-radius: 20px;
  --button-radius: 20px;
  --size-4-2: 8px;
  --size-4-3: 12px;
  --size-4-4: 16px;
  --size-4-6: 24px;
  --size-4-8: 32px;
  --h1-size: 36px; --h1-weight: 400; --h1-line-height: 1.15;
  --h2-size: 26px; --h2-weight: 400;
  --h3-size: 21px; --h3-weight: 500;
  --h4-size: 17px; --h4-weight: 500;
  --h5-size: 15px; --h5-weight: 500;
  --h6-size: 15px; --h6-weight: 500;
  --bold-weight: 600;
}}

.theme-dark, .theme-light {{
  --background-primary: {raised};
  --background-primary-alt: {raised};
  --background-secondary: {base};
  --background-secondary-alt: {base};
  --titlebar-background: {base};
  --titlebar-background-focused: {base};
  --background-modifier-border: rgba({rgb(fg)}, .08);
  --background-modifier-border-hover: rgba({rgb(fg)}, .12);
  --background-modifier-border-focus: rgba({rgb(fg)}, .24);
  --background-modifier-hover: rgba({rgb(fg)}, .10);
  --background-modifier-active-hover: rgba({rgb(fg)}, .14);
  --background-modifier-form-field: rgba({rgb(fg)}, .06);
  --background-modifier-message: {raised};
  --background-modifier-error: {c["red"]};
  --background-modifier-success: {c["green"]};
  --divider-color: transparent;
  --divider-color-hover: transparent;
  --divider-width: 0px;
  --tab-outline-width: 0px;
  --tab-divider-color: transparent;
  --tab-background-active: rgba({rgb(fg)}, .14);
  --tab-text-color-focused-active: {fg};
  --nav-item-background-active: rgba({rgb(fg)}, .14);
  --nav-item-background-hover: rgba({rgb(fg)}, .10);
  --nav-item-color-active: {fg};
  --nav-item-weight-active: 500;
  --text-normal: {fg};
  --text-muted: {muted};
  --text-faint: {muted};
  --text-on-accent: {"#ffffff" if light else base};
  --text-selection: {sel};
  --text-highlight-bg: rgba({rgb(c["yellow"])}, .25);
  --text-accent: {accent};
  --text-accent-hover: {accent};
  --interactive-normal: rgba({rgb(fg)}, .06);
  --interactive-hover: rgba({rgb(fg)}, .10);
  --interactive-accent: {accent};
  --interactive-accent-hover: {accent};
  --text-title-h1: {fg}; --text-title-h2: {fg}; --text-title-h3: {fg};
  --text-title-h4: {fg}; --text-title-h5: {fg}; --text-title-h6: {muted};
  --text-link: {accent};
  --link-color: {accent};
  --link-external-color: {accent};
  --link-decoration: none;
  --code-normal: {fg};
  --code-background: rgba({rgb(fg)}, .06);
  --code-comment: {muted};
  --code-keyword: {c["blue"]};
  --code-string: {c["green"]};
  --code-value: {c["yellow"]};
  --code-function: {c["magenta"]};
  --code-property: {c["cyan"]};
  --blockquote-border-color: {accent};
  --blockquote-border-thickness: 2px;
  --hr-color: rgba({rgb(fg)}, .12);
  --hr-thickness: 2px;
  --checkbox-color: {accent};
  --checkbox-color-hover: {accent};
  --checkbox-border-color: {muted};
  --checkbox-radius: 8px;
  --tag-color: {accent};
  --tag-color-hover: {accent};
  --tag-background: rgba({rgb(accent)}, .12);
  --tag-background-hover: rgba({rgb(accent)}, .18);
  --tag-radius: 20px;
  --tag-padding-x: 12px;
  --tag-padding-y: 4px;
  --tag-weight: 500;
  --scrollbar-thumb-bg: rgba({rgb(fg)}, .14);
  --scrollbar-active-thumb-bg: rgba({rgb(fg)}, .24);
  --scrollbar-bg: transparent;
  --graph-line: {muted};
  --graph-node: {accent};
  --graph-node-focused: {fg};
  --graph-node-tag: {c["cyan"]};
  --graph-node-attachment: {c["green"]};
  --text-error: {c["red"]};
  --text-success: {c["green"]};
  --modal-radius: 24px;
  --prompt-border-width: 1px;
  --shadow-s: {shadow};
  --shadow-l: {shadow};
}}

/* The interface stays Inter even where a pane inherits the text font. */
.workspace-tab-header, .nav-file-title, .nav-folder-title, .status-bar, .view-header-title, .prompt, .modal, .menu, .suggestion-container {{ font-family: var(--font-interface-theme); }}

/* Headings are hierarchy by size and weight, not colour. h1 is tracked in. */
.markdown-rendered h1, .cm-header-1 {{ letter-spacing: -0.02em; }}
.markdown-rendered h2, .cm-header-2 {{ letter-spacing: -0.01em; }}

/* Panes are surfaces: raised editor on the base sidebar, a hairline between. */
.workspace-split.mod-root .workspace-tabs .workspace-leaf, .workspace-leaf-content {{ background: var(--background-primary); }}
.workspace-tab-header-container, .workspace-ribbon, .status-bar, .side-dock-ribbon, .view-header {{ border: none; }}
.workspace-tab-header.is-active .workspace-tab-header-inner {{ border-radius: 20px; }}
.workspace-tab-header-inner {{ padding: 0 16px; }}
.status-bar {{ padding: 0 24px; }}

/* Code: the one place monospace belongs. */
.markdown-rendered code, .cm-inline-code {{ border-radius: 8px; padding: 2px 6px; }}
.markdown-rendered pre, .HyperMD-codeblock {{ border-radius: 12px; }}

/* Controls are the text colour at alpha; focus is a deeper fill and a hairline, never an accent outline. */
button, .clickable-icon {{ border-radius: 20px; }}
input[type=text], input[type=search], .prompt-input {{ border-radius: 20px; background: var(--background-modifier-form-field); border: none; min-height: 40px; }}
input[type=text]:focus, input[type=search]:focus, .prompt-input:focus {{ background: rgba({rgb(fg)}, .10); box-shadow: 0 0 0 1px rgba({rgb(fg)}, .24); }}

/* Callouts are tinted surfaces with a hairline, never a coloured band. */
.callout {{ border: 1px solid rgba({rgb(fg)}, .08); border-radius: 24px; padding: 24px; }}
.callout .callout-title {{ font-family: var(--font-interface-theme); font-weight: 500; }}
"""

PICKER = """@define-color foreground {fg};
@define-color background {raised};
@define-color base {base};
@define-color accent {accent};
@define-color muted {muted};

/* Marvin: the screen-share picker in the system's own terms. Inter, 14px,
   a hairline on the window, cards at the nested radius, the one filled
   control is the confirm button. Generated by tools/appcss.py. */
* {{
  all: unset;
  font-family: Inter, sans-serif;
  font-weight: 400;
  font-size: 14px;
  color: @foreground;
}}
.window {{ background: @background; border: 1px solid alpha(@foreground, 0.08); border-radius: 24px; margin: 0; padding: 24px; }}
tabs {{ padding: 0 0 16px 0; }}
tabs > tab {{ margin-right: 8px; padding: 0 20px; min-height: 40px; border-radius: 20px; }}
.tab-label {{ color: @muted; }}
tabs > tab:checked, tabs > tab:active {{ background: alpha(@foreground, 0.14); }}
tabs > tab:checked > .tab-label, tabs > tab:active > .tab-label {{ color: @foreground; }}
tabs > tab:focus {{ box-shadow: inset 0 0 0 1px alpha(@foreground, 0.24); }}
.page {{ padding: 0; }}
.image-label {{ font-size: 12px; color: @muted; padding: 8px 0 0 0; }}
flowboxchild > .card, button > .card {{ border: none; border-radius: 12px; background-color: alpha(@foreground, 0.06); padding: 8px; }}
flowboxchild:hover > .card, button:hover > .card {{ background-color: alpha(@foreground, 0.10); }}
flowboxchild:selected > .card, button:active > .card, button:selected > .card {{ background-color: alpha(@foreground, 0.14); }}
flowboxchild:focus > .card, button:focus > .card {{ box-shadow: 0 0 0 1px alpha(@foreground, 0.24); }}
.image {{ border-radius: 8px; }}
.region-button {{ min-height: 40px; padding: 0 20px; border-radius: 20px; background-color: @foreground; color: @background; }}
.region-button > label {{ color: @background; }}
.region-button:not(:disabled):hover, .region-button:not(:disabled):focus {{ opacity: 0.85; }}
.region-button:disabled {{ background-color: alpha(@foreground, 0.06); color: @muted; }}
.region-button:disabled > label {{ color: @muted; }}
"""

if __name__ == "__main__":
    for light, pre in ((False, ""), (True, "light/")):
        c = toml(ROOT / f"{pre}colors.toml")
        (ROOT / f"{pre}obsidian.css").write_text(obsidian(c, light))
        (ROOT / f"{pre}hyprland-preview-share-picker.css").write_text(PICKER.format(fg=c["foreground"], raised=c["lighter_background"], base=c["background"], accent=c["accent"], muted=c["muted"]))
        print("wrote", f"{pre}obsidian.css", f"{pre}hyprland-preview-share-picker.css")
