#!/usr/bin/env python3
"""Generate the app stylesheets the theme ships, from colors.toml.

    tools/appcss.py            # writes obsidian.css and the share-picker css for both tones

Obsidian: Inter for the interface, Libre Baskerville (falling back to Noto Serif)
for note text, monospace only inside code; radius 24, padding 24, hairline
surfaces, two text tones, neutral headings, chips for tags.
"""
import re, pathlib
ROOT = pathlib.Path(__file__).resolve().parent.parent

def toml(p):
    d = {}
    for l in open(p):
        m = re.match(r'^\s*([A-Za-z0-9_-]+)\s*=\s*"([^"]*)"', l)
        if m: d[m.group(1)] = m.group(2)
    return d
def rgb(h): return ",".join(str(int(h[i:i+2], 16)) for i in (1, 3, 5))

def obsidian(c, light):
    base, raised, fg, muted, accent, sel = c["background"], c["lighter_background"], c["foreground"], c["muted"], c["accent"], c["selection"]
    atext = c.get("accent_text", accent)   # the accent is a graphic colour (3:1); text set in it uses the deeper accent_text
    shadow = "0 8px 32px rgba(0,0,0,.06)" if light else "0 8px 32px rgba(0,0,0,.28)"
    # control alphas follow shell.toml [controls]: light 0.04/0.05/0.07 + ring 0.12, dark 0.06/0.10/0.14 + ring 0.24
    hov, sel, ring = (".05", ".07", ".12") if light else (".10", ".14", ".24")
    return f"""/* Marvin for Obsidian — {'light' if light else 'dark'}. Generated by tools/appcss.py
   from colors.toml. The design system applied to the Notes app: Inter for
   the interface, a serif for the notes themselves, monospace only inside
   code; radius 24, padding 24, hairline surfaces, two text tones, neutral
   headings, chips for tags. */

body {{
  --font-interface-theme: "Inter", sans-serif;
  --font-text-theme: "Libre Baskerville", "Baskerville", "Noto Serif", serif;
  --font-monospace-theme: "JetBrains Mono", monospace;
  --font-text-size: 17px;
  --font-ui-smaller: 12px;
  --font-ui-small: 12px;
  --font-ui-medium: 14px;
  --font-ui-large: 16px;
  --line-height-normal: 1.6;
  --file-line-width: 40em;
  --radius-s: 12px;
  --radius-m: 24px;
  --radius-l: 24px;
  --radius-xl: 24px;
  --tab-radius: 20px;
  --input-radius: 20px;
  --button-radius: 20px;
  --size-4-2: 8px;
  --size-4-3: 12px;
  --size-4-4: 16px;
  --size-4-6: 24px;
  --size-4-8: 32px;
  --h1-size: 36px; --h1-weight: 400; --h1-line-height: 1.15;
  --h2-size: 26px; --h2-weight: 400;
  --h3-size: 21px; --h3-weight: 500;
  --h4-size: 17px; --h4-weight: 500;
  --h5-size: 15px; --h5-weight: 500;
  --h6-size: 15px; --h6-weight: 500;
  --bold-weight: 600;
}}

.theme-dark, .theme-light {{
  --background-primary: {raised};
  --background-primary-alt: {raised};
  --background-secondary: {base};
  --background-secondary-alt: {base};
  --titlebar-background: {base};
  --titlebar-background-focused: {base};
  --background-modifier-border: rgba({rgb(fg)}, .08);
  --background-modifier-border-hover: rgba({rgb(fg)}, .12);
  --background-modifier-border-focus: rgba({rgb(fg)}, {ring});
  --background-modifier-hover: rgba({rgb(fg)}, {hov});
  --background-modifier-active-hover: rgba({rgb(fg)}, .14);
  --background-modifier-form-field: rgba({rgb(fg)}, .06);
  --background-modifier-message: {raised};
  --background-modifier-error: {c["red"]};
  --background-modifier-success: {c["green"]};
  --divider-color: transparent;
  --divider-color-hover: transparent;
  --divider-width: 0px;
  --tab-outline-width: 0px;
  --tab-divider-color: transparent;
  --tab-background-active: rgba({rgb(fg)}, .14);
  --tab-text-color-focused-active: {fg};
  --nav-item-background-active: rgba({rgb(fg)}, .14);
  --nav-item-background-hover: rgba({rgb(fg)}, {hov});
  --nav-item-color-active: {fg};
  --nav-item-weight-active: 500;
  --text-normal: {fg};
  --text-muted: {muted};
  --text-faint: {muted};
  --text-on-accent: {"#ffffff" if light else base};
  --text-selection: {sel};
  --text-highlight-bg: rgba({rgb(c["yellow"])}, .25);
  --text-accent: {atext};
  --text-accent-hover: {atext};
  --interactive-normal: rgba({rgb(fg)}, .06);
  --interactive-hover: rgba({rgb(fg)}, {hov});
  --interactive-accent: {accent};
  --interactive-accent-hover: {accent};
  --text-title-h1: {fg}; --text-title-h2: {fg}; --text-title-h3: {fg};
  --text-title-h4: {fg}; --text-title-h5: {fg}; --text-title-h6: {muted};
  --text-link: {atext};
  --link-color: {atext};
  --link-external-color: {atext};
  --link-decoration: none;
  --code-normal: {fg};
  --code-background: rgba({rgb(fg)}, .06);
  --code-comment: {muted};
  --code-keyword: {c["blue"]};
  --code-string: {c["green"]};
  --code-value: {c["yellow"]};
  --code-function: {c["magenta"]};
  --code-property: {c["cyan"]};
  --blockquote-border-color: {accent};
  --blockquote-border-thickness: 2px;
  --hr-color: rgba({rgb(fg)}, .12);
  --hr-thickness: 2px;
  --checkbox-color: {accent};
  --checkbox-color-hover: {accent};
  --checkbox-border-color: {muted};
  --checkbox-radius: 8px;
  --tag-color: {atext};
  --tag-color-hover: {atext};
  --tag-background: rgba({rgb(accent)}, .12);
  --tag-background-hover: rgba({rgb(accent)}, .18);
  --tag-radius: 20px;
  --tag-padding-x: 12px;
  --tag-padding-y: 4px;
  --tag-weight: 500;
  --scrollbar-thumb-bg: rgba({rgb(fg)}, .14);
  --scrollbar-active-thumb-bg: rgba({rgb(fg)}, {ring});
  --scrollbar-bg: transparent;
  --graph-line: {muted};
  --graph-node: {accent};
  --graph-node-focused: {fg};
  --graph-node-tag: {c["cyan"]};
  --graph-node-attachment: {c["green"]};
  --text-error: {c["red"]};
  --text-success: {c["green"]};
  --modal-radius: 24px;
  --prompt-border-width: 1px;
  --shadow-s: {shadow};
  --shadow-l: {shadow};
}}

/* The interface stays Inter even where a pane inherits the text font. */
.workspace-tab-header, .nav-file-title, .nav-folder-title, .status-bar, .view-header-title, .prompt, .modal, .menu, .suggestion-container {{ font-family: var(--font-interface-theme); }}

/* Headings are hierarchy by size and weight, not colour. h1 is tracked in. */
.markdown-rendered h1, .cm-header-1 {{ letter-spacing: -0.02em; }}
.markdown-rendered h2, .cm-header-2 {{ letter-spacing: -0.01em; }}

/* Panes are surfaces: raised editor on the base sidebar, a hairline between. */
.workspace-split.mod-root .workspace-tabs .workspace-leaf, .workspace-leaf-content {{ background: var(--background-primary); }}
.workspace-tab-header-container, .workspace-ribbon, .status-bar, .side-dock-ribbon, .view-header {{ border: none; }}
.workspace-tab-header.is-active .workspace-tab-header-inner {{ border-radius: 20px; }}
.workspace-tab-header-inner {{ padding: 0 16px; }}
.status-bar {{ padding: 0 24px; }}

/* Code: the one place monospace belongs. */
.markdown-rendered code, .cm-inline-code {{ border-radius: 8px; padding: 2px 6px; }}
.markdown-rendered pre, .HyperMD-codeblock {{ border-radius: 12px; }}

/* Every control moves: 120 ms on fill, colour and ring, the same scale as the compositor's shortest step. */
button, .clickable-icon, .nav-file-title, .nav-folder-title, .tag, .tab-header, .workspace-tab-header, .suggestion-item, .menu-item, input[type=text], input[type=search], .prompt-input, .checkbox-container {{ transition: background-color .12s ease, color .12s ease, box-shadow .12s ease, opacity .12s ease; }}
.clickable-icon:hover, .nav-file-title:hover, .nav-folder-title:hover, .menu-item:hover, .suggestion-item:hover, .workspace-tab-header:hover {{ background-color: rgba({rgb(fg)}, {hov}); }}
@media (prefers-reduced-motion: reduce) {{ button, .clickable-icon, .nav-file-title, .nav-folder-title, .tag {{ transition: none; }} }}

/* Controls are the text colour at alpha; focus is a deeper fill and a hairline, never an accent outline. */
button, .clickable-icon {{ border-radius: 20px; }}
input[type=text], input[type=search], .prompt-input {{ border-radius: 20px; background: var(--background-modifier-form-field); border: none; min-height: 40px; }}
input[type=text]:focus, input[type=search]:focus, .prompt-input:focus {{ background: rgba({rgb(fg)}, {sel}); box-shadow: 0 0 0 1px rgba({rgb(fg)}, {ring}); }}

/* Callouts are tinted surfaces with a hairline, never a coloured band. */
.callout {{ border: 1px solid rgba({rgb(fg)}, .10); border-radius: 24px; padding: 24px; }}
.callout .callout-title {{ font-family: var(--font-interface-theme); font-weight: 500; }}
"""

PICKER = """@define-color foreground {fg};
@define-color background {raised};
@define-color base {base};
@define-color accent {accent};
@define-color muted {muted};

/* Marvin: the screen-share picker in the system's own terms. Inter, 14px,
   a hairline on the window, cards at the nested radius, the one filled
   control is the confirm button. Generated by tools/appcss.py. */
* {{
  all: unset;
  font-family: Inter, sans-serif;
  font-weight: 400;
  font-size: 14px;
  color: @foreground;
}}
.window {{ background: @background; border: 1px solid alpha(@foreground, 0.10); border-radius: 24px; margin: 0; padding: 24px; }}
tabs > tab, flowboxchild > .card, button > .card, .region-button {{ transition: background-color 120ms ease, box-shadow 120ms ease, opacity 120ms ease; }}
tabs > tab:hover {{ background: alpha(@foreground, {hov}); }}
tabs {{ padding: 0 0 16px 0; }}
tabs > tab {{ margin-right: 8px; padding: 0 20px; min-height: 40px; border-radius: 20px; }}
.tab-label {{ color: @muted; }}
tabs > tab:checked, tabs > tab:active {{ background: alpha(@foreground, {sel}); }}
tabs > tab:checked > .tab-label, tabs > tab:active > .tab-label {{ color: @foreground; }}
tabs > tab:focus {{ box-shadow: inset 0 0 0 1px alpha(@foreground, {ring}); }}
.page {{ padding: 0; }}
.image-label {{ font-size: 12px; color: @muted; padding: 8px 0 0 0; }}
flowboxchild > .card, button > .card {{ border: none; border-radius: 12px; background-color: alpha(@foreground, {nrm}); padding: 8px; }}
flowboxchild:hover > .card, button:hover > .card {{ background-color: alpha(@foreground, {hov}); }}
flowboxchild:selected > .card, button:active > .card, button:selected > .card {{ background-color: alpha(@foreground, {sel}); }}
flowboxchild:focus > .card, button:focus > .card {{ box-shadow: 0 0 0 1px alpha(@foreground, {ring}); }}
.image {{ border-radius: 8px; }}
.region-button {{ min-height: 40px; padding: 0 20px; border-radius: 20px; background-color: @foreground; color: @background; }}
.region-button > label {{ color: @background; }}
.region-button:not(:disabled):hover, .region-button:not(:disabled):focus {{ opacity: 0.85; }}
.region-button:disabled {{ background-color: alpha(@foreground, 0.06); color: @muted; }}
.region-button:disabled > label {{ color: @muted; }}
"""

def colmap(c):
    """Omarchy's colorN + role names, resolved to Marvin hex. The ANSI order is
    background, red, green, yellow, blue, magenta, cyan, foreground, muted."""
    return dict(
        background=c["background"], foreground=c["foreground"], accent=c["accent"],
        cursor=c.get("bright_foreground", c["foreground"]),
        selection_background=c["selection"], selection_foreground=c.get("bright_foreground", c["foreground"]),
        color0=c["background"], color1=c["red"], color2=c["green"], color3=c["yellow"],
        color4=c["blue"], color5=c["magenta"], color6=c["cyan"], color7=c["foreground"], color8=c["muted"],
    )

# btop: Omarchy's own key mapping (default/themed/btop.theme.tpl), filled from
# Marvin's palette. The ANSI colours are already soft, so the meters read quiet.
BTOP = '''theme[main_bg]="{background}"
theme[main_fg]="{foreground}"
theme[title]="{foreground}"
theme[hi_fg]="{accent}"
theme[selected_bg]="{color8}"
theme[selected_fg]="{accent}"
theme[inactive_fg]="{color8}"
theme[graph_text]="{foreground}"
theme[meter_bg]="{color8}"
theme[proc_misc]="{foreground}"
theme[cpu_box]="{color5}"
theme[mem_box]="{color2}"
theme[net_box]="{color1}"
theme[proc_box]="{accent}"
theme[div_line]="{color8}"
theme[temp_start]="{color2}"
theme[temp_mid]="{color3}"
theme[temp_end]="{color1}"
theme[cpu_start]="{color6}"
theme[cpu_mid]="{color4}"
theme[cpu_end]="{color5}"
theme[free_start]="{color5}"
theme[free_mid]="{color4}"
theme[free_end]="{color6}"
theme[cached_start]="{color4}"
theme[cached_mid]="{color6}"
theme[cached_end]="{color5}"
theme[available_start]="{color3}"
theme[available_mid]="{color1}"
theme[available_end]="{color1}"
theme[used_start]="{color2}"
theme[used_mid]="{color6}"
theme[used_end]="{color4}"
theme[download_start]="{color3}"
theme[download_mid]="{color1}"
theme[download_end]="{color1}"
theme[upload_start]="{color2}"
theme[upload_mid]="{color6}"
theme[upload_end]="{color4}"
theme[process_start]="{color6}"
theme[process_mid]="{color4}"
theme[process_end]="{color5}"
'''

def btop(c):
    return "# Marvin for btop. Generated by tools/appcss.py from colors.toml.\n" + BTOP.format(**colmap(c))

def chromium(c):
    """Omarchy sets Chromium's frame colour from the background as R,G,B."""
    return rgb(c["background"]) + "\n"

# helix: the scope map is Omarchy's (default/themed/helix.toml.tpl); scopes
# reference palette names, and [palette] below binds them to Marvin's hex.
HELIX_SCOPES = '''# Marvin for Helix. Generated by tools/appcss.py from colors.toml.
# Syntax
"keyword" = "color5"
"keyword.control" = { fg = "color5", modifiers = ["italic"] }
"function" = "color4"
"function.builtin" = "color4"
"function.macro" = "color5"
"type" = "color3"
"type.builtin" = "color5"
"type.enum.variant" = "color6"
"constructor" = "color4"
"constant" = "color3"
"constant.builtin" = "color3"
"constant.numeric" = "color3"
"constant.character" = "color6"
"constant.character.escape" = "color5"
"string" = "color2"
"string.regexp" = "color5"
"string.special" = "color4"
"comment" = { fg = "color8", modifiers = ["italic"] }
"variable" = "foreground"
"variable.parameter" = { fg = "color5", modifiers = ["italic"] }
"variable.builtin" = "color1"
"variable.other.member" = "color4"
"label" = "color4"
"punctuation" = "color8"
"punctuation.special" = "color6"
"operator" = "color6"
"tag" = "color4"
"namespace" = { fg = "color3", modifiers = ["italic"] }
"special" = "color5"
"attribute" = "color3"

# Markup
"markup.heading.1" = "color1"
"markup.heading.2" = "color3"
"markup.heading.3" = "color3"
"markup.heading.4" = "color2"
"markup.heading.5" = "color4"
"markup.heading.6" = "color5"
"markup.list" = "color6"
"markup.list.unchecked" = "color8"
"markup.list.checked" = "color2"
"markup.bold" = { fg = "color1", modifiers = ["bold"] }
"markup.italic" = { fg = "color1", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "color4", modifiers = ["italic", "underlined"] }
"markup.link.text" = "color5"
"markup.link.label" = "color4"
"markup.raw" = "color2"
"markup.quote" = "color5"

# Diff
"diff.plus" = "color2"
"diff.minus" = "color1"
"diff.delta" = "color4"

# Leave the editor background transparent so the terminal background shows through
"ui.background" = { }

"ui.linenr" = { fg = "color8" }
"ui.linenr.selected" = { fg = "foreground" }

"ui.statusline" = { fg = "background", bg = "foreground" }
"ui.statusline.inactive" = { fg = "background", bg = "color8" }
"ui.statusline.normal" = { fg = "background", bg = "color4", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "background", bg = "color2", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "background", bg = "color5", modifiers = ["bold"] }

"ui.popup" = { fg = "foreground", bg = "background" }
"ui.window" = { fg = "color8" }
"ui.help" = { fg = "foreground", bg = "background" }

"ui.bufferline" = { fg = "color8", bg = "background" }
"ui.bufferline.active" = { fg = "foreground", bg = "background", underline = { color = "color5", style = "line" } }

"ui.text" = "foreground"
"ui.text.focus" = { fg = "foreground", bg = "color0", modifiers = ["bold"] }
"ui.text.inactive" = { fg = "color8" }
"ui.text.directory" = { fg = "color4" }

"ui.virtual" = "color8"
"ui.virtual.ruler" = { bg = "color0" }
"ui.virtual.indent-guide" = "color8"
"ui.virtual.inlay-hint" = { fg = "color8" }
"ui.virtual.jump-label" = { fg = "color1", modifiers = ["bold"] }
"ui.virtual.whitespace" = "color8"

"ui.selection" = { bg = "selection_background", fg = "selection_foreground" }

"ui.cursor" = { fg = "background", bg = "cursor" }
"ui.cursor.primary" = { fg = "background", bg = "cursor" }
"ui.cursor.match" = { fg = "color3", modifiers = ["bold"] }
"ui.cursor.primary.normal" = { fg = "background", bg = "cursor" }
"ui.cursor.primary.insert" = { fg = "background", bg = "color2" }
"ui.cursor.primary.select" = { fg = "background", bg = "color5" }

"ui.cursorline.primary" = { bg = "color0" }

"ui.highlight" = { bg = "color0", modifiers = ["bold"] }

"ui.menu" = { fg = "foreground", bg = "background" }
"ui.menu.selected" = { fg = "background", bg = "foreground", modifiers = ["bold"] }

"diagnostic.error" = { underline = { color = "color1", style = "curl" } }
"diagnostic.warning" = { underline = { color = "color3", style = "curl" } }
"diagnostic.info" = { underline = { color = "color4", style = "curl" } }
"diagnostic.hint" = { underline = { color = "color6", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

error = "color1"
warning = "color3"
info = "color4"
hint = "color6"
'''

def helix(c):
    m = colmap(c)
    palette = "\n".join(f'{k} = "{m[k]}"' for k in (
        "background", "foreground", "cursor", "selection_background", "selection_foreground",
        "color0", "color1", "color2", "color3", "color4", "color5", "color6", "color7", "color8"))
    return HELIX_SCOPES + "\n[palette]\n" + palette + "\n"

if __name__ == "__main__":
    for light, pre in ((False, ""), (True, "light/")):
        c = toml(ROOT / f"{pre}colors.toml")
        (ROOT / f"{pre}obsidian.css").write_text(obsidian(c, light))
        (ROOT / f"{pre}hyprland-preview-share-picker.css").write_text(PICKER.format(fg=c["foreground"], raised=c["lighter_background"], base=c["background"], accent=c["accent"], muted=c["muted"], **(dict(nrm="0.04", hov="0.05", sel="0.07", ring="0.12") if light else dict(nrm="0.06", hov="0.10", sel="0.14", ring="0.24"))))
        (ROOT / f"{pre}btop.theme").write_text(btop(c))
        (ROOT / f"{pre}chromium.theme").write_text(chromium(c))
        (ROOT / f"{pre}helix.toml").write_text(helix(c))
        print("wrote", f"{pre}{{obsidian.css, hyprland-preview-share-picker.css, btop.theme, chromium.theme, helix.toml}}")
